server:
  port: 9093
  servlet:
    context-path: /contact
    
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: hr
    password: hr
    
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      

    